<h3>Q1: Explain the difference between a Python list and a NumPy array in terms of memory usage and performance.Then, write a program that creates both and performs element-wise multiplication.</h3>
<p>Ans. Python lists and NumPy arrays are both used to store data, but they are different internally.

A Python list can store heterogenious elements. Each element in the list is stored as a separate object in memory, only references (addresses) to those objects is stored in List. Because of this, lists consume more memory and are slower for numerical calculations.

A NumPy array stores elements of the same data type in contiguous memory locations. Since the data is stored in a continuous block, memory usage is lower and operations are much faster.
</p>


In [2]:
import numpy as np

lst1 = [1,2,3,4,5]
lst2 = [10,20,30,40,50]

lst1_X_lst2 = [lst1[i]*lst2[i] for i in range(len(lst2))]

print(f"Multiplication using list: {lst1_X_lst2}")

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr1_X_arr2 = arr1*arr2

print(f"Multiplication using Numpy array: {arr1_X_arr2}")


Multiplication using list: [10, 40, 90, 160, 250]
Multiplication using Numpy array: [ 10  40  90 160 250]


<h3>Q2: What is broadcasting in NumPy?Create a 3×3 NumPy array and add a 1D array to it using broadcasting. Explain how NumPy applies the operation internally</h3>

<p>Ans. Broadcasting is a feature in NumPy that allows arithmetic operations between arrays of different shapes. NumPy automatically adjusts the smaller array to match the larger one without actually copying data.

HOW:
The shape of A is (3,3) and the shape of B is (3,).
NumPy treats B as if it were repeated for each row:
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
This process is automatic and does not create any copy in memory</p>

In [3]:
arr1 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

arr2 = np.array([10, 20, 30])

r = arr1+arr2
print(r)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


<h3> Q3: What are missing values in Pandas and how are they represented?Create a DataFrame with missing values and write code to: </h3>
<ul>
<li>Detect missing values</li>
<li>Replace them with the column mean</li>
</ul>
 <h4>Explain each step</h4>

<p>Ans. Missing values are data values that are not available or not entered. In Pandas, missing values are represented using:
<ul>
<li>NaN (Not a Number)</li>
<li>None</li>
</ul>

In [4]:
import pandas as pd
data = {
    'Name': ['Aman','Harsh','Devesh','Tushar'],
    'Marks': [90,np.nan, 75,80],
    'Age':[20,19,np.nan,18]
}
df = pd.DataFrame(data)
print(df)

     Name  Marks   Age
0    Aman   90.0  20.0
1   Harsh    NaN  19.0
2  Devesh   75.0   NaN
3  Tushar   80.0  18.0


In [5]:
#Detecting missing values
print(df.isnull())
print(df.isnull().sum())
# isnull() returns True where values are missing.
# sum() counts how many missing values are present in each column.

    Name  Marks    Age
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
Name     0
Marks    1
Age      1
dtype: int64


In [6]:
#filling missing values with mean
df['Marks']=df['Marks'].fillna(df['Marks'].mean())
df['Age']=df['Age'].fillna(df['Age'].mean())
print(df)
# Here, mean() calculates the average of available values.
# fillna() replaces NaN with that average value.

     Name      Marks   Age
0    Aman  90.000000  20.0
1   Harsh  81.666667  19.0
2  Devesh  75.000000  19.0
3  Tushar  80.000000  18.0


<h3>
Q4: Explain boolean indexing in NumPy or Pandas.Create a DataFrame with at least 5 columns and filter rows based on two conditionsusing logical operators. Explain how filtering works internally
</h3>
<p>Ans. Boolean indexing means selecting rows based on conditions. It returns only the rows where the condition is True.</p>


In [7]:
data = {
    'Name': ['Aman','Harsh','Devesh','Tushar'],
    'Marks': [90,70, 75,80],
    'Age':[20,19,15,18],
    'Sem':[4,6,2,8],
    'Dept': ['CS','CE','ME','EE']
}

df = pd.DataFrame(data)
filtered_data = df[(df['Marks']>80) & (df['Dept']=='CS')]
print(filtered_data)

   Name  Marks  Age  Sem Dept
0  Aman     90   20    4   CS


<h5>HOW:</h5><p>First condition before '&' checks if Marks are greater than 80 and second condition checks if Dept is CS then returns data according to it</p>

<h3>
Q5: What is the purpose of the groupby() function in Pandas? Create a DataFrame with categorical data (e.g., department & salary) and calculatethe average salary per department using groupby(). Explain the output.
</h3>
<p>
The groupby() function is used to group data based on categories and perform aggregate operations like mean, sum, count, etc.

It follows three steps:
<ul>
<li>Split the data into groups.</li>
<li>Apply a function.</li>
<li>Combine the results.</li>
</ul>
</p>


In [9]:
data = {
    'Name': ['Aman','Harsh','Devesh','Tushar'],
    'Marks': [90,70, 75,80],
    'Age':[20,19,15,18],
    'Sem':[4,6,2,8],
    'Dept': ['CS','CE','ME','EE']
}
df = pd.DataFrame(data)
avg_marks = df.groupby('Dept')['Marks'].mean()
print(avg_marks)

Dept
CE    70.0
CS    90.0
EE    80.0
ME    75.0
Name: Marks, dtype: float64


<p>Explanation:
<ul>
<li>The data is grouped according to Department.</li>
<li>Then mean Marks is calculated for each department.</li>
<li>The output shows average Marks department-wise.</li>
</ul>
</p>